### ISSUE TITLE
Concept Class CPT4?

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/OMOP-Standardized-Vocabularies#13]
Why is concept_class 'CPT4' still in the latest vocab? for example concept_id = 2213225

This should not be in there anymore correct according to the wiki correct?:
https://github.com/OHDSI/CommonDataModel/wiki/CONCEPT_CLASS

**Comment by cgreich** [comment]
Why not? We have three concept classes in the CPT4 vocabulary:

- CPT4: The ordinary CPT4 concepts
- CPT4 Hierarchy: higher level summary concepts
- CPT4 Modifier: To modify (add attributes) to the CPT4 concepts.

It's all good. What do you think the problem is?

**Comment by aostropolets** [comment]
I believe Peter’s referring to the wiki page, which says that in v5 concept_class_id CPT-4 was changed to Procedure

**Comment by PRijnbeek** [comment]
Indeed. I read that as if this should not be a concept_class anymore.

It is also to me strange to give the concept_class the name of a vocabulary considering this sentence:

"The CONCEPT_CLASS table is a reference table, which includes a list of the classifications used to differentiate Concepts **within a given Vocabulary**"

CPT4 itself is not a classification system so I think it should not be the name of concept_class?

"Procedures" would make much more sense to me, as is what is written on the wiki-page.

By the way, it is somewhat strange still that concepts in the Measurement domain can have a concept_class "Procedure", but I understand that these are procedures that have a result...?

**Comment by aostropolets** [comment]
The thing is that the procedural nature of CPT concepts is represented by their domain_id and most of the concepts apriori are procedures. We use concept_class_id ‘CPT4’ here in order to distinguish between the ordinary CPT4 concepts, hierarchical concepts and modifiers, although all of them belong to procedures.

“By the way, it is somewhat strange still that concepts in the Measurement domain can have a concept_class "Procedure", but I understand that these are procedures that have a result...?”
Yep. They mean that you’be done a procedure like, for instance, microscopy, culture etc. in 4057441 Identification of microorganisms in CSF, but you still can put into an actual result.

**Comment by cgreich** [comment]
Well, the thing is that the documentation is way behind, and we have been procrastinating fixing it up for a long time, really. (Scratching egg off face).
