### ISSUE TITLE
PPI concepts moved to Measurement domain from Observation?  v5.0 17-MAR-19

### ISSUE THREAD

**Issue by ksdkalluri** [OHDSI/OMOP-Standardized-Vocabularies#35]
All of Us Research Program has been using v5.0 22-DEC-17 and we are planning to upgrade to v5.0 17-MAR-19.  In **Concept** table there are a lot of concepts for which the domain has been changed since the old version for the PPI Vocabulary. 
for eg.

```sql
select *
from v1.concept 
where concept_id in (1585596, 1585597, 1585598, 1585260, 1585252, 1585246, 1585247, 1585248, 1585249, 1585250, 1585259)
```

gives result

![Screen Shot 2019-04-08 at 2 40 55 PM](https://user-images.githubusercontent.com/23404801/55748597-1848a700-5a0d-11e9-99fc-7a68af2c38bf.png)

```sql
select *
from v2.concept 
where concept_id in (1585596, 1585597, 1585598, 1585260, 1585252, 1585246, 1585247, 1585248, 1585249, 1585250, 1585259)
```

gives result 

![Screen Shot 2019-04-08 at 2 43 04 PM](https://user-images.githubusercontent.com/23404801/55748515-ed5e5300-5a0c-11e9-809f-1eac08a47a2c.png)

To make sure I checked http://athena.ohdsi.org for one of the concept_id from the above query **1585260** which is concept_id for e-mail. I found out that the `Non-standard to Standard map(OMOP)` is linked to `LOINC`  instead of `PPI`. 

![Screen Shot 2019-04-08 at 2 53 19 PM](https://user-images.githubusercontent.com/23404801/55749039-14695480-5a0e-11e9-8c82-3acd0e9aa08c.png)

For all the concepts with `Non-standard to Standard map(OMOP)` linked to `LOINC` Vocabulary instead of `PPI`, the domain is being changed from `observation` to `measurement`.

But most of the concepts like e-mail, First_name, phone etc. belong to `Observation` domain rather that the `measurement`. 

is this change intentional?  

we also found that 139 PPI to PPI  concept_ancestor records missing in the new version, Not sure if it both are related.

**Comment by p-talapova** [comment]
> is this change intentional?

Let me clarify the matter. Initially, all source concepts are considered to be Non-standard. Only after the mapping their domains can be defined.  Being mapped to Standard concept source concept inherit its domain. Not being mapped to a Standard concept a source concept becomes standard and get a domain whichever you prefer. 

The old PPI mapping logic (whose results we are seeing in Athena now) is the following:
1) All PPI source concepts have one-to-one mapping.
2) If PPI source concepts have standard equivalents in SNOMED or LOINC, they are considered to be Non-standard
3) If PPI source concepts do not have standard equivalents in SNOMED or LOINC, they are considered to be Standard
4) The domains used for Questions are 'Measurement' and 'Observation' (depending on the existence of a mapping to a Standard concept). 
5) The domains used for an Answers vary. They can be represented by Observation, Meas Value, Condition or Procedure.

Due to regular PPI mapping refreshes (we have already performed 6 ones), domains of PPI vocabulary was being changed respectively .

According to the 'valid_start_date' field in the CONCEPT_RELATIONSHIP table, domains of PPI concepts you mentioned were assigned either in 2017-09-12 (the second version of the mapping) or in 2018-08-15 (the fifth one). That was fine in respect of the old PPI mapping logic. But the times have changed. 

Currently we are working on the implementation of the new PPI mapping logic (see the diagram below). 
![PPI logic diagram](https://user-images.githubusercontent.com/42737398/55786889-ca3fac00-5abd-11e9-9048-cf71d12c35a3.png)
Long story short,  all PPI source concepts  will get 'Observation' domain to be easily connected with the SURVEY_CONDUCT table. To aim this, we are also changing the domain distribution of the LOINC vocabulary which is widely used in mappings of any survey-related entities as well as PPI Questions. 

So very soon you will see improved structure of PPI vocabulary, which can be used as a target vocabulary for mappings of other questionnaires to standard concepts in the future (in the PPI, the are currently 1237 standard concepts).      

> we also found that 139 PPI to PPI concept_ancestor records missing in the new version, Not sure if it both are related.

The hierarchy was also being modified due to the customer requests.  Could you provide us with the list of these PPI concepts to let us confirm the relevance of such changes?

**Comment by ksdkalluri** [comment]
This is very helpful, Thank you.
