### ISSUE TITLE
Vocabulary Concepts with no Equivalent Standard Concept

### ISSUE THREAD

**Issue by noahgengel** [OHDSI/OMOP-Standardized-Vocabularies#44]
Hello,

After some investigation, Zoey and I (both from CUMC) found that many sites struggled to map some of their local concepts to 'standard' concepts because no equivalent exists in the standard vocabulary. To document these gaps in the language, we wanted to list the nonstandard concepts that have no corresponding standard mapping:

**_ICD10/ICD10CM_**:
**R76.8**: Other specified abnormal immunological findings in serum
**R78.9**: Finding of unspecified substance, not normally found in blood
**R74.8**: Abnormal levels of other serum enzymes
**R74.9**: Abnormal serum enzyme level, unspecified
**R76.9**: Abnormal immunological finding in serum unspecified
**R77.8**: Other specified abnormalities of plasma proteins (NOTE: we found standard concepts that were unidirectional. In other words, we found a measurement for 'low' plasma proteins but not 'high' or 'general abnormal' plasma proteins).
**R77.9**: Abnormality of plasma protein, unspecified
**Z51.81**: THERAPEUTIC DRUG LEVEL MONITOR
**R97.8**: Other abnormal tumor markers
**R77.0**: Abnormality of albumin (NOTE: there are some standard concepts relating to albumin abnormalities but these are too specific)
**Z68.54**: BMI PEDIATRIC GREAT THAN OR EQUAL TO 95% FOR AGE
**Z6851**: BMI PEDIATRIC, LESS THAN 5TH PERCENTILE FOR AGE
**Z72.61**: Antibody Response Examination
**V72.32**: Encounter for Papanicolaou cervical smear to confirm findings of recent normal smear following initial abnormal smear
**Z13.79**: ECT FOR OT SCREEN FOR GENETC&CHROMSOML ANOMALITY
**R77.1**: Abnormality of Globulin (NOTE: there are specific abnormalities listed as standard concepts)
**V72.63**: Pre-Procedural Laboratory Examination
**V72.62**:LABORATORY EXAMINATION ORDERED AS PART OF A ROUTINE GENERAL MEDICAL EXAMINATION
**Z0283**: ENCOUNTER FOR BLOOD-ALCOHOL AND BLOOD-DRUG TEST (NOTE: we have been normally classifying 'encounters' as procedures rather than measurements)
**Z0182**:ENCOUNTER FOR ALLERGY TESTING
**Z0142**:ECT FOR CERV SMR - CNFRM NORM SMR FOL INI AB
**Z0184**:ENCOUNTER FOR ANTIBODY RESPONSE EXAMINATION

**_ICD9/ICD9CM_**:
**790.6**: OTHER ABNORMAL BLOOD CHEMISTRY
**795.79**: Other and unspecified nonspecific immunological findings
**790.5**: Other nonspecific abnormal serum enzyme levels
**792.9**: OTHER NONSPECIFIC ABNORMAL FINDINGS IN BODY
**794.2**: NONSPECIFIC ABNORMAL RESULTS OF PULMONARY FUNCTION STUDY
**796.0**: NONSPECIFIC ABNORMAL TOXICOLOGICAL FINDINGS
**795.08**: UNSATISFACTORY CERVICAL CYTOLOGY SMEAR
**791.7**: OTHER CELLS AND CASTS IN URINE

**_Local Vocabulary (not on Athena)_**:
- FLOW CYTOMETRY, CD4 AND CD8
- FLOW CYTOMETRY, CD4
- FLOW CYTOMETRY, PNH
- FLOW CYTOMETRY T,B,NK LYMPHOCYTE COUNTS (with the flow cytometry it seems like there are obstacles when it comes to all of the combinations of cell types)
- EMG / NCS Testing (current codes list EMG and NCS separately; parent of both codes is too vague)
- CHEM 7 PANEL (HISTORICAL): NOTE - The current best fit for this in the 'Measurement' domain is 3041230. This ID, however, does not include sodium in the panel.
- PAIN MANAGEMENT PROFILE

We recognize that this is a long list and that not all of these codes will warrant the creation of a new standard concept but thought it would not hurt to document everything we saw here. We also recognize that some of these codes technically have standard concepts in Athena but, after inspection, realized that the 'standard' mapping leaves out crucial information (e.g. going from abnormal findings to a general measurement.)

Please let either of us know if you have any questions or concerns.

Thank you,
Noah Engel

**Comment by cgreich** [comment]
@noahgengel:

Yeah. There are a few problems with them:

* Most of them are Measurements, but so unspecific that you cannot use them for analytics. Essentially they all are "Measurement of something, with no result provided". You can't map that junk to anything useful. Take R76.8: "Other specified abnormal immunological findings in serum" - what use case will this record fulfill? 
* Some of them are artifacts to get reimbursed, such as V72.62 "LABORATORY EXAMINATION ORDERED AS PART OF A ROUTINE GENERAL MEDICAL EXAMINATION". For analytics completely useless.

Your Local codes just need to be mapped:

* FLOW CYTOMETRY, CD4 AND CD8: I assume that is in blood for HIV, is it not? How about http://athena.ohdsi.org/search-terms/terms/40768448
* FLOW CYTOMETRY, CD4: Same thing. http://athena.ohdsi.org/search-terms/terms/40768447
* FLOW CYTOMETRY, PNH: http://athena.ohdsi.org/search-terms/terms/40758294
* FLOW CYTOMETRY T,B,NK LYMPHOCYTE COUNTS (with the flow cytometry it seems like there are obstacles when it comes to all of the combinations of cell types): http://athena.ohdsi.org/search-terms/terms/40768449. However, this is a panel. It's B-cell, T-cell and NK cell counts using surface markers. You need to write three separate MEASUREMENT records and put the results into the respective tests.
* EMG / NCS Testing (current codes list EMG and NCS separately; parent of both codes is too vague): Understood. But what does the record actually say? One *or* the other? Again, pretty useless for analytics. You can't look for patients that "maybe" have had one of two tests, and you have no idea what the result refers to. Junk code.
* CHEM 7 PANEL (HISTORICAL): NOTE - The current best fit for this in the 'Measurement' domain is 3041230. This ID, however, does not include sodium in the panel: It's a panel. So, you would need to write out the individual tests anyway. Because the MEASUREMENT table can only give results for one test at a time.
* PAIN MANAGEMENT PROFILE: What's that? Drug in urine testing for pain and addiction management? Again, you need to cut this panel into pieces anyway.

Hope this helps. Keep it coming. BTW: The Forum is probably the better place for this generic debate.

**Comment by noahgengel** [comment]
@cgreich Thank you! As a follow-up question:

Generally speaking, can we map to a panel? For example, for the [CD4/8 code you suggested](http://athena.ohdsi.org/search-terms/terms/40768448), what would the value truly represent? Since you said that a measurement can only have one value, how would we be able to differentiate the CD4 and CD8 values in the CD4/8 standard panel?

Thank you for all of your help,
Noah

**Comment by cgreich** [comment]
No. You need to resolve the panel into individual Measurement to provide the results.
